# Generated by Django 4.2 on 2024-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networklink',
            name='model',
        ),
        migrations.RemoveField(
            model_name='networklink',
            name='title',
        ),
        migrations.AddField(
            model_name='networklink',
            name='model_product',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Модель продукта'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='title_product',
            field=models.CharField(default='Название по умолчанию', max_length=255, verbose_name='Название продукта'),
        ),
    ]
